# Scaffolding generated by Casein v5.0.0.0

module Casein
  class PostSectionsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Post sections'
  		@post_sections = PostSection.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View post section'
      @post_section = PostSection.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new post section'
    	@post_section = PostSection.new
    end

    def create
      @post_section = PostSection.new post_section_params
    
      if @post_section.save
        flash[:notice] = 'Post section created'
        redirect_to casein_post_sections_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new post section'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update post section'
      
      @post_section = PostSection.find params[:id]
    
      if @post_section.update_attributes post_section_params
        flash[:notice] = 'Post section has been updated'
        redirect_to casein_post_sections_path
      else
        flash.now[:warning] = 'There were problems when trying to update this post section'
        render :action => :show
      end
    end
 
    def destroy
      @post_section = PostSection.find params[:id]

      @post_section.destroy
      flash[:notice] = 'Post section has been deleted'
      redirect_to casein_post_sections_path
    end
  
    private
      
      def post_section_params
        params.require(:post_section).permit(:name)
      end

  end
end