default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  port: 5432
  user: od4d
 

development:
  <<: *default
  database: od4d

test:
  <<: *default
  database: od4d

staging:
  <<: *default
  database: od4d

production:
  <<: *default
  database: od4d
